openapi: 3.0.0
x-stoplight:
  id: i5yczhey972ww
info:
  title: main
  contact: {}
  version: '1.0'
servers:
  - url: 'https://stoplight.io/mocks/college-app/college-app/406762'
    description: Mock Server
    variables: {}
paths:
  /login:
    post:
      summary: Login
      description: |
        ## 概要
        accessTokenを取得するためのエンドポイント。

        初期登録フォーム未回答の場合、User情報を取得する。

        ## レスポンスによるクライアント側の分岐

        - 200
          - レスポンスにuserがある
            - 初期登録フォームに遷移、default値にuserを使用
          - レスポンスにuserがない
            - Homeに遷移
        - 401
          - 「このエラーが出たら運営に報告してね」エラーページに遷移
        - 403
          - 「このアカウントは無効化されてるよ」エラーページに遷移
        - 404
          - 「まだ運営側でデータ登録が完了していないよ」エラーページに遷移
      operationId: post-login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: false
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 無効なfirebaseIdToken
          headers: {}
          content: {}
        '403':
          description: Disabledになっている、つまりBANされているアカウント
          headers: {}
          content: {}
        '404':
          description: |-
            Airtable上にデータが存在しません

            先にAirtableでEmailだけでも登録してください
          headers: {}
          content: {}
      deprecated: false
  /users:
    put:
      summary: Update Me
      description: Airtable上の自分のUser情報をアップデートする
      operationId: put-users
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
        required: false
      responses:
        '200':
          description: OK
          headers: {}
          content: {}
      deprecated: false
      security:
        - accessToken: []
    get:
      summary: Get Users
      description: 全てのユーザーを取得する
      operationId: get-users
      parameters: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                description: ''
      deprecated: false
      security:
        - accessToken: []
  /users/search:
    get:
      summary: Search Users
      description: |-
        ## TODO

        - [ ] フィルタリング
        - [ ] ページネーション
      operationId: get-users-search
      parameters:
        - name: query
          in: query
          description: 検索ワード
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                description: ''
      deprecated: false
      security:
        - accessToken: []
  '/users/{recordId}':
    get:
      summary: Get User
      description: 指定のuserを取得
      operationId: get-users-recordId
      parameters:
        - name: recordId
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      deprecated: false
      security:
        - accessToken: []
  /generations:
    get:
      summary: Get Generations
      description: 指定したtypeの`Generation`を全て取得する
      operationId: get-generations
      parameters:
        - schema:
            type: string
            enum:
              - program
              - house
          in: query
          name: type
          required: true
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Generation'
                description: ''
      deprecated: false
      security:
        - accessToken: []
  '/generations/{recordId}':
    get:
      summary: Get Generation
      description: 指定のgenerationを取得
      operationId: get-generations-recordId
      parameters:
        - name: recordId
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'
        '404':
          description: Not Found
      deprecated: false
      security:
        - accessToken: []
  /groups:
    get:
      summary: Get Groups
      description: 指定したtypeの`Group`を全て取得する
      operationId: get-groups
      parameters:
        - schema:
            type: string
            enum:
              - committee
              - club
          in: query
          name: type
          required: true
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
                description: ''
      deprecated: false
      security:
        - accessToken: []
  '/groups/{recordId}':
    get:
      summary: Get Group
      description: 指定のGroupを取得
      operationId: get-groups-recordId
      parameters:
        - name: recordId
          in: path
          description: ''
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
        '404':
          description: Not Found
      deprecated: false
      security:
        - accessToken: []
  /social-brands:
    get:
      summary: Get SocialBrands
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SocialBrand'
      operationId: get-social-brands
      security:
        - accessToken: []
      description: Social Brandを全て取得する
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
          description: Airtable's Record ID
        email:
          type: string
          example: hoge@hlab.college
          format: email
        role:
          $ref: '#/components/schemas/Role'
        i18n:
          type: array
          items:
            $ref: '#/components/schemas/UserI18n'
        imageUrl:
          type: string
          format: uri
        pronoun:
          $ref: '#/components/schemas/Pronoun'
        birthday:
          type: string
          format: date
        hideAge:
          type: boolean
          default: false
        socialLinks:
          type: array
          items:
            $ref: '#/components/schemas/UserSocialLink'
        roomNumber:
          maximum: 599
          minimum: 100
          type: number
        postNumber:
          maximum: 599
          minimum: 100
          type: number
        selfIntroductionSlideUrl:
          type: string
          format: uri
        programs:
          type: array
          items:
            $ref: '#/components/schemas/Generation'
        houses:
          type: array
          items:
            $ref: '#/components/schemas/Generation'
        committees:
          type: array
          items:
            $ref: '#/components/schemas/UserGroupBelonging'
        clubs:
          type: array
          items:
            $ref: '#/components/schemas/UserGroupBelonging'
        position:
          type: string
          description: 肩書き
        bio:
          type: string
          description: Markdown
        photoUrls:
          type: array
          items:
            type: string
            format: uri
        lastModifiedAt:
          type: string
          format: date
      required:
        - id
        - email
        - role
        - i18n
    UserI18n:
      title: UserI18n
      type: object
      properties:
        locale:
          $ref: '#/components/schemas/Locale'
        firstName:
          type: string
        lastName:
          type: string
        phoneticFirstName:
          type: string
        phoneticLastName:
          type: string
        nickName:
          type: string
        middleName:
          type: string
        phoneticMiddleName:
          type: string
        maidenName:
          type: string
        prefix:
          type: string
        suffix:
          type: string
      required:
        - locale
        - firstName
        - lastName
    UserGroupBelonging:
      title: UserGroupBelonging
      type: object
      properties:
        group:
          $ref: '#/components/schemas/Group'
        displayName:
          type: string
          example: カレッジライフ分科会 (22.04~)
        from:
          type: string
          format: date
        to:
          type: string
          format: date
      required:
        - group
        - displayName
    UserSocialLink:
      title: UserSocialLink
      required:
        - brand
        - username
      type: object
      properties:
        brand:
          $ref: '#/components/schemas/SocialBrand'
        username:
          type: string
          example: chiji1108
    SocialBrand:
      title: SocialBrand
      type: object
      properties:
        id:
          type: string
          description: Airtable's Record ID
        name:
          type: string
          example: twitter
        svgIconUrl:
          type: string
          format: uri
        urlPrefix:
          type: string
          example: 'https://twitter.com/'
          format: uri
        formPrefix:
          type: string
          example: '@'
      required:
        - id
        - name
    Group:
      title: Group
      type: object
      description: '`Committee`, `Club`のモデル'
      properties:
        id:
          type: string
          description: Airtable's Record ID
        type:
          $ref: '#/components/schemas/GroupType'
        displayName:
          type: string
        createdAt:
          type: string
          format: date
        archivedAt:
          type: string
          format: date
        emoji:
          type: string
          example: "\U0001F4DA"
        title:
          type: string
          example: カレッジライフ分科会
        description:
          type: string
          description: Markdown
        slackChannel:
          type: string
          example: '#310_coco_collegelife'
        photoUrls:
          type: array
          items:
            type: string
            format: uri
      required:
        - id
        - type
        - displayName
    Generation:
      title: Generation
      type: object
      description: '`Program`, `House`のモデル'
      properties:
        id:
          type: string
          description: Airtable's Record ID
        type:
          $ref: '#/components/schemas/GenerationType'
        displayName:
          type: string
          example: RP2期生
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        coverImageUrl:
          type: string
          format: uri
        title:
          type: string
          example: Residential Program 2期生
        description:
          type: string
          description: Markdown
        photoUrls:
          type: array
          items:
            type: string
            format: uri
      required:
        - id
        - type
        - displayName
    Locale:
      title: Locale
      enum:
        - ja
        - en
      type: string
      x-stoplight:
        id: b45329b541c5a
      description: Enum
    Pronoun:
      title: Pronoun
      enum:
        - SHE_HER
        - HE_HIM
        - THEY_THEM
      type: string
      description: Enum
    Role:
      title: Role
      enum:
        - resident
        - alumni
        - staff
      type: string
      description: Enum
    GroupType:
      title: GroupType
      x-stoplight:
        id: 2dwof9ol7jw5s
      type: string
      enum:
        - committee
        - club
        - project
      description: Enum
    GenerationType:
      title: GenerationType
      x-stoplight:
        id: guoy130cad7y7
      type: string
      enum:
        - program
        - house
      description: Enum
    UpdateUserRequest:
      title: UpdateUserRequest
      x-stoplight:
        id: u3favfr7srwr4
      type: object
      properties:
        i18n:
          type: array
          items:
            type: object
            properties:
              locale:
                $ref: '#/components/schemas/Locale'
              firstName:
                type: string
              lastName:
                type: string
              phoneticFirstName:
                type: string
              phoneticLastName:
                type: string
              nickName:
                type: string
              middleName:
                type: string
              phoneticMiddleName:
                type: string
              maidenName:
                type: string
              prefix:
                type: string
              suffix:
                type: string
            required:
              - locale
        imageUrl:
          type: string
          format: uri
        pronoun:
          $ref: '#/components/schemas/Pronoun'
        birthday:
          type: string
          format: date
        hideAge:
          type: boolean
          default: false
        socialLinks:
          type: array
          items:
            type: object
            properties:
              brandId:
                type: string
                description: Airtable's Record ID
              username:
                type: string
            required:
              - brandId
              - username
        roomNumber:
          maximum: 599
          minimum: 100
          type: number
        postNumber:
          maximum: 599
          minimum: 100
          type: number
        selfIntroductionSlideUrl:
          type: string
          format: uri
        generations:
          type: array
          description: Airtable's Record IDs
          items:
            type: string
        groups:
          type: array
          items:
            type: object
            properties:
              groupId:
                type: string
                description: Airtable's Record ID
              from:
                type: string
                format: date
              to:
                type: string
                format: date
            required:
              - groupId
        position:
          type: string
          description: 肩書き
        bio:
          type: string
          description: Markdown
        photoUrls:
          type: array
          items:
            type: string
            format: uri
        lastModifiedAt:
          type: string
          format: date
      description: ''
    LoginResponse:
      title: LoginResponse
      x-stoplight:
        id: wirdxz0ka60a9
      type: object
      description: 初期登録フォーム未回答の場合、userも返す
      properties:
        accessToken:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - accessToken
    LoginRequest:
      title: LoginRequest
      x-stoplight:
        id: bq3lg3312kxji
      type: object
      properties:
        firebaseIdToken:
          type: string
          description: '取得方法は[こちら](https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients)'
      required:
        - firebaseIdToken
      description: ''
  securitySchemes:
    accessToken:
      type: http
      description: |-
        `Authrization: Bearer <accessToken>`

        `accessToken`は`/login`で取得する。
      scheme: bearer
security: []
tags: []
