# This is a basic workflow to help you get started with Actions

name: generate

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch and petstore.yaml
on:
  push:
    branches: [ main ]
    paths: main.yaml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1

    # openapi generate
    - run: |
        npm install @openapitools/openapi-generator-cli -g
        npx @openapitools/openapi-generator-cli generate -i main.yaml -g typescript-fetch -o /dist/ts-client
        npx @openapitools/openapi-generator-cli generate -i main.yaml -g swift5 -o /dist/swift-client
        npx @openapitools/openapi-generator-cli generate -i main.yaml -g rust-server -o /dist/server

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
